import { createReadStream, createWriteStream } from "node:fs";
import { mkdir, readFile, rm, stat } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { objectStorageClient } from "../lib/object-storage";

// Byte storage for campaign delivery media (V2-05B). Keys are generated by
// the server only (never from a request), and every backend refuses a key
// that would leave its root. Two backends:
//  - object storage (production): the private bucket/prefix in
//    PRIVATE_OBJECT_DIR, through the existing App Storage client;
//  - local disk (development and tests only): CAMPAIGN_MEDIA_STORAGE_DIR,
//    ignored when NODE_ENV is production.
// Without either, uploads answer 503 media_storage_unavailable; nothing
// falls back to a public bucket or a URL.

export interface CampaignMediaStore {
  readonly kind: "object_storage" | "local_disk";
  put(key: string, body: AsyncIterable<Buffer>): Promise<void>;
  read(key: string, maxBytes: number): Promise<Buffer>;
  stream(key: string): Readable;
  remove(key: string): Promise<void>;
}

const KEY_PATTERN = /^organizations\/\d+\/campaigns\/\d+\/media\/[0-9a-f-]{36}$/;

export function assertMediaKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error("Invalid campaign media storage key");
}

export class LocalDiskMediaStore implements CampaignMediaStore {
  readonly kind = "local_disk" as const;
  constructor(private readonly root: string) {}

  private file(key: string): string {
    assertMediaKey(key);
    const resolved = path.resolve(this.root, key);
    const relative = path.relative(path.resolve(this.root), resolved);
    if (relative.startsWith("..") || path.isAbsolute(relative)) throw new Error("Campaign media key escapes the storage root");
    return resolved;
  }

  async put(key: string, body: AsyncIterable<Buffer>): Promise<void> {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await pipeline(Readable.from(body), createWriteStream(file, { flags: "wx" }));
  }

  async read(key: string, maxBytes: number): Promise<Buffer> {
    const file = this.file(key);
    const info = await stat(file);
    if (info.size > maxBytes) throw new Error("Stored campaign media is larger than allowed");
    return readFile(file);
  }

  stream(key: string): Readable {
    return createReadStream(this.file(key));
  }

  async remove(key: string): Promise<void> {
    await rm(this.file(key), { force: true });
  }
}

export class ObjectStorageMediaStore implements CampaignMediaStore {
  readonly kind = "object_storage" as const;
  constructor(private readonly bucketName: string, private readonly prefix: string) {}

  private object(key: string) {
    assertMediaKey(key);
    const name = this.prefix ? `${this.prefix}/${key}` : key;
    return objectStorageClient.bucket(this.bucketName).file(name);
  }

  async put(key: string, body: AsyncIterable<Buffer>): Promise<void> {
    await pipeline(Readable.from(body), this.object(key).createWriteStream({ resumable: false, metadata: { cacheControl: "private, no-store" } }));
  }

  async read(key: string, maxBytes: number): Promise<Buffer> {
    const [metadata] = await this.object(key).getMetadata();
    if (Number(metadata.size ?? 0) > maxBytes) throw new Error("Stored campaign media is larger than allowed");
    const [bytes] = await this.object(key).download();
    return bytes;
  }

  stream(key: string): Readable {
    return this.object(key).createReadStream();
  }

  async remove(key: string): Promise<void> {
    await this.object(key).delete({ ignoreNotFound: true });
  }
}

let override: CampaignMediaStore | null | undefined;

/** Tests only: install (or clear with undefined) a store. */
export function setCampaignMediaStoreForTests(store: CampaignMediaStore | null | undefined): void {
  override = store;
}

export function configuredCampaignMediaStore(env: NodeJS.ProcessEnv = process.env): CampaignMediaStore | null {
  if (override !== undefined) return override;
  const privateDir = env.PRIVATE_OBJECT_DIR?.trim().replace(/\/+$/, "");
  if (privateDir) {
    const parts = privateDir.replace(/^\/+/, "").split("/");
    if (parts[0]) return new ObjectStorageMediaStore(parts[0], [...parts.slice(1), "campaign-media"].join("/"));
  }
  const localDir = env.CAMPAIGN_MEDIA_STORAGE_DIR?.trim();
  if (localDir && env.NODE_ENV !== "production") return new LocalDiskMediaStore(localDir);
  return null;
}
